### ISSUE TITLE
connect errors

### ISSUE THREAD

**Issue by uvstarr97** [MayankFawkes/Python-Botnet#12]
i bought domain with host and i cant connect client with server also im running server using putty and i have 3vps to open client and when i added ip:port of my host it dont work help

**Comment by MayankFawkes** [comment]
it seems your port is not accessible, you can try to `telnet` your ip and port to check if the port is accepting connection and if not then you can enable your firewall of your vps with `ufw` and allow server port.

**Comment by Nixxxss** [comment]
but im not connecting to vps like i connecting client and serer to domain for using putty
to use it

**Comment by MayankFawkes** [comment]
things are pretty unclear for me, could you please explain more.

**Comment by Nixxxss** [comment]
can i have ur discord?

**Comment by MayankFawkes** [comment]
`DiceOfDeath#0227`
