### ISSUE TITLE
I didn't understand how this token works

### ISSUE THREAD

**Issue by henriquefbarrado** [MayankFawkes/Python-Botnet#16]
bro, I need help I've been trying to solve this for 30 minutes but I can't, how do I add the client? 
![image](https://user-images.githubusercontent.com/87922671/214745479-79177824-fe7f-4fa9-9aab-4358322637a6.png)

**Comment by MayankFawkes** [comment]
I am guessing your clients are trying to connect some different port, please try to keep the same port on server and client also make sure your server ip is accessible from client VM.
