### ISSUE TITLE
just to clarify

### ISSUE THREAD

**Issue by JonatWells** [MayankFawkes/Python-Botnet#4]
for the format: attack udp <12.113.232.212> <80> <10> <not exactly sure still what goes here?> is this the proper format or do i have to include the words "IP" and "Port"?

**Comment by MayankFawkes** [comment]
The formate is `attack udp 127.0.0.1 80 60 2` This will start 2 bot and start flooding on your localhost on port 80 for 1 minute.

Disclaimer: as i have seen you are attacking on some public IP i am hoping thats your server IP or you doing that with permission attacking some random server is illigal and you may get in trouble, we dont accept any illigal usage of this script, we made it for education purpose thanks.

**Comment by JonatWells** [comment]
Oh that’s not a real IP, I copied mine and just replaced some random numbers, thanks for the help!

**Comment by MayankFawkes** [comment]
Your welcome 😃

**Comment by JonatWells** [comment]
Hey I got it all set up, one issue, I compiled an exe and had my friend run
it on his pc (with his permission of course) the thing is, his pc didn’t
show up on the list

**Comment by MayankFawkes** [comment]
I am not sure what you mean by that and how you made/get the exe. If you made exe file from .py file then client can workout console but server cant work without that. I am still not aware what you mean by list.

**Comment by JonatWells** [comment]
I compiled the client into an exe, I mean when I’m on my server py, I run
the command “list” to see all my connected bots yet that one doesn’t show
up.

**Comment by JonatWells** [comment]
Hey add me on discord Marcell#6515 maybe I can show you what I mean

**Comment by MayankFawkes** [comment]
I think you are not aware of port forwarding and all. If you used it on WAN then you must have to edit client file and edit your IP and port then you need to open the same port from your internet router or you can use ngrok for that. For more you must read about port forwarding on internet.
