### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by MeWhenCum** [MayankFawkes/Python-Botnet#5]
I know I'm suppose to change something here, but please help me.
When I try to run "python Server.py"
I'm left with this error

File "Server.py", line 66
    def __init__(self, connect:Tuple[str,int]=("0.0.0.0",9999)):
                              ^
SyntaxError: invalid syntax

**Comment by MayankFawkes** [comment]
Check your python version with `python --version` make sure to use python3.x.

**Comment by MeWhenCum** [comment]
> Check your python version with `python --version` make sure to use python3.x.

THANKS!!!!!!
