### ISSUE TITLE
new

### ISSUE THREAD

**Issue by SORZIEZ** [MayankFawkes/Python-Botnet#8]
so im new to python and have no clue what im doing is there a special file type to use and how do I execute it and one more thing how do I use the command list kill, list, ping, etc

**Comment by MayankFawkes** [comment]
Hey sorry for late response, all you need to install python3.6 or above then run the server.py and client.py respectively.

**Comment by reaperawdasd** [comment]
how do i get this to run maybe a tutorial or just a txt file with the commands

**Comment by MayankFawkes** [comment]
Sure i will send it tomorrow morning.

**Comment by SDLresearch** [comment]
Is possible you send how to run: the server.py and client.py respectively. I tried to perform an attack but it didn't work. Thanks
